### ISSUE TITLE
Add support for releasing `securedrop-sdk` without using a debian package repo, e.g. `securedrop-client`

### ISSUE THREAD

**Issue by sssoleileraaa** [freedomofpress/securedrop-builder#203]
## Description

Updated Aug 3, 2021:

To release `securedrop-sdk` you have to do more or less [what I did here](https://github.com/freedomofpress/build-logs/commit/2e77c0657424c86256a5a4336d310f3772cd4036#diff-b7748a9410798dd2f5d65f9fd49b2019c8a47ed26627a1550d36a50caceffb62) so that the debian packaging tool can use its regular logic to build any missing wheels for a debian package. 

What you don't see in the build logs is the first part of the process where we build the source tarball and wheel using `python3 -m build`, delete the built wheel, and then upload the source tarball to PyPI via `python3 -m twine upload --repository pypi dist/*`. 

This all works, but:
* We have a docs problem in the `securedrop-sdk` because we don't explain _why_ we are using a debian packaging tool to build something that is not a debian package. Plus we just point to the "how to build a debian package" docs and leave it up to the dev to figure out that you need to use a debian packaging tool to build a wheel and there are no instructions about updating `securedrop-client` requiremetns and building that as a debian package in order to build the wheel for the sdk. We should better explain not only how this works but why we do this (answer: we want to build the wheel reproducibly).
* When releasing a new sdk wheel using an external debian project, we get poorly-timed updated dependencies for that external project, requiring diff reviews for a release that is not actually happening), e.g.:
```
~/workspace/freedomofpress/securedrop-debian-packaging(main⚡) » git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   sha256sums.txt
	modified:   sha256sums.txt.asc

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	localwheels/MarkupSafe-1.1.1-cp37-cp37m-linux_x86_64.whl
	localwheels/securedrop-sdk-0.2.0.tar.gz
	localwheels/securedrop_sdk-0.2.0-py3-none-any.whl

no changes added to commit (use "git add" and/or "git commit -a")
```
* Even if we were to be releasing the debian project at the same time we release the new wheel, it would be better if prod dependency updates were part of some nightly job or something rather than waiting last minute until a release.
* PyPI and our PyPI mirror end up out of sync becuase we don't actually upload the wheel built with our own tooling to PyPI. It would be cleaner if we waited until the wheel was built before publishing a new version of the sdk to PyPI.

**Comment by creviera** [comment]
Which way is preferred for creating and uploading the SDK wheels:

1. check out the new tag for the SDK
2.  `python3 setup.py sdist` and upload the tarball to PyPi
3. cd to debian packaging repo and run `PKG_DIR=../securedrop-sdk make build-wheels`
4. after someone like mickael signs the new wheels, upload the wheels to FPF PyPi

or 

1. check out the new tag for the SDK
2.  `python3 setup.py sdist` and upload the tarball to PyPi
3. check out client code on `main`
4. update requirements.in to securedrop-sdk 0.2.0
5. cd to debian packaging repo and run `PKG_DIR=../securedrop-client make build-wheels`
6. after someone like mickael signs the new sdk wheels, upload the wheels to FPF PyPi

the second method mickael mentioned, although I'm not sure if it's preferred because we're not ready to update the use the latest sdk in the client, and it's more steps.

**Comment by creviera** [comment]
Looks like `MarkupSafe-1.1.1-py3-none-any.whl` and `MarkupSafe-1.1.1-cp37-cp37m-linux_x86_64.whl` are the same 1.1.1 version, so I ended up removing the cp37m wheel that is generated from running `make build-wheels`. (Note: MarkupSafe is used by `mako` which is used by `alembic`.)

The next QA session will catch any errors this may cause, but since there hasn't been any upgrades to the package, there shouldn't be an issue with sticking to the _any_ wheel rather than switching to the _manylinux_ wheel. I also would like to do some research into manylinux and why we this binary wheel of MarkupSafe was released. In the meantime, we should be fine with releasing a new version of the client and SDK without this change. Depending on what I learn/ depending on what Kushal or others on the team think about same-version manylinux builds, we might want to include some kind of instructions in our docs to ignore them, unless there is an actual version upgrade.

> Which way is preferred for creating and uploading the SDK wheels:

As far as my second question goes, I discussed this with Kushal and the reason for updating the client requirements and building sdk wheels that way (the second set up steps I listed above) is to also release any updated dependencies other than the sdk at the same time. So it's meant to save time, since we have to release a new version of the client deb each time we update the SDK.

I think we can make the docs a bit clearer by first updating the `securedrop-sdk` readme to mention that you have to release a new version of the client any time you need to update the sdk wheels, and to link to the client release process docs which should also link out to the securedrop-debian-packaging docs. I'll be looking for other ways to make it easier to follow, but for now just going to add a new docs issue.

**Comment by creviera** [comment]
> I think we can make the docs a bit clearer by first updating the securedrop-sdk readme to mention that you have to release a new version of the client any time you need to update the sdk wheels, and to link to the client release process docs which should also link out to the securedrop-debian-packaging docs. I'll be looking for other ways to make it easier to follow, but for now just going to add a new docs issue.

The process for releasing a new version of the sdk remains pretty obscure based on what we currently have in the docs. I think we should decouple an SDK release from the client release procedure. Right now, in order to release the SDK you have to do what I did here: https://github.com/freedomofpress/build-logs/commit/2e77c0657424c86256a5a4336d310f3772cd4036#diff-b7748a9410798dd2f5d65f9fd49b2019c8a47ed26627a1550d36a50caceffb62. I will re-title and update this issue description to be clearer about why this is a problem, and I think it's more than a docs problem.

**Comment by legoktm** [comment]
AIUI, currently securedrop-sdk is embedded in the securedrop-client package as its installed in the venv, so any update to the sdk needs a new client package to be issued.

Once thing I've been thinking about is shipping the securedrop-sdk as its own package, that the securedrop-client package would install into its venv as part of the postinst with something like `pip install -e /path/to/securedrop-sdk`, so when the sdk package is updated, the client venv is updated. I'm not exactly sure how dependencies would work with this, given that they need to be in sync between the sdk and the client if they go into the same venv.

**Comment by legoktm** [comment]
Another option would be to better model the way the securedrop-sdk is deployed in our Git development process, possibly by using a git submodule. Then it's more obvious that the sdk is a subcomponent of the client, etc. and needs to be bumped/released in coordination.

**Comment by legoktm** [comment]
We are no longer releasing the SDK separately, it is now just a subfolder in the client.
