### ISSUE TITLE
Rename some packaging-related repos

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-builder#304]
# Description

(This issue is to track the renaming of other repos as well. Just capturing the details of the new naming format here.)

There's a growing consensus around renaming some package repos to adhere to this format: `securedrop-{apt,yum}-{test,prod}` and also to rename this repo to `securedrop-builder`. To make it explicit, here is the list of repos that we'd like to rename:

* `securedrop-debian-packaging` -> `securedrop-builder`
* `securedrop-dev-packages-lfs` -> `securedrop-apt-test`
* `securedrop-debian-packages-lfs` -> `securedrop-apt-prod`
* `securedrop-workstation-dev-rpm-packages-lfs` -> `securedrop-yum-test`
* `securedrop-workstation-prod-rpm-packages-lfs` -> `securedrop-yum-prod`

Still an open discussion, so additional suggestions are welcome.

**Comment by legoktm** [comment]
Should we make a final call for objections and/or +1s? Probably we should start with one of the test repos just to make sure everything follows GitHub's redirects properly.

**Comment by creviera** [comment]
@freedomofpress/securedrop-maintainers ^ 

Also, this Issue is already on our team board so we can ask for objections and/or +1s one more time in the upcoming sprint and then prioritize a spike towards this migration.

**Comment by eloquence** [comment]
Perhaps `securedrop-workstation-builder` would be more descriptive for this repo, given that it doesn't (currently) handle anything related to SD server builds? Otherwise SGTM.

**Comment by kushaldas** [comment]
- `securedrop-yum-test` -> `securedrop-dnf-test`
- `securedrop-yum-prod` -> `securedrop-dnf-test`

Just s/yum/dnf :) Otherwise looks okay to me.

**Comment by eloquence** [comment]
How do folks therefore feel about this revised rename operation:

- securedrop-debian-packaging -> securedrop-workstation-builder
- securedrop-dev-packages-lfs -> securedrop-apt-test
- securedrop-debian-packages-lfs -> securedrop-apt-prod
- securedrop-workstation-dev-rpm-packages-lfs -> securedrop-dnf-test
- securedrop-workstation-prod-rpm-packages-lfs -> securedrop-dnf-prod

(No opinion on the dnf vs. yum naming; I will note that the repos are still called yum.securedrop.org and yum-test.securedrop.org)

**Comment by creviera** [comment]
```
* `securedrop-debian-packaging` -> `securedrop-builder`
* `securedrop-dev-packages-lfs` -> `securedrop-apt-test`
* `securedrop-debian-packages-lfs` -> `securedrop-apt-prod`
* `securedrop-workstation-dev-rpm-packages-lfs` -> `securedrop-yum-test`
* `securedrop-workstation-prod-rpm-packages-lfs` -> `securedrop-yum-prod`
```
I prefer the suggestion currently in the issue description (pasting here just in case it changes later) because a) shorter names and abbreviations that you can pronounce as words, e.g. `yum` instead of `dnf` are easier to talk about in conversation, b) making the lfs repos match their corresponding hosted package repos is kinda nice, and c) I think the goal is to consolidate more of our deb builder code between workstation and server, so `securedrop-builder` works nicely for that.

**Comment by creviera** [comment]
Now that I'm working on infra with @maeve-fpf, I'd like to offer my help and suggest that we start on the apt repos (first apt-test) since we're all in agreement there:

* securedrop-dev-packages-lfs -> securedrop-apt-test
* securedrop-debian-packages-lfs -> securedrop-apt-prod

@cfm - Just throwing this on your radar in case you find time to incorporate a facilitated discussion in an upcoming SD team meeting around the other suggestions for our rpms and builder.

**Comment by gonzalo-bulnes** [comment]
I've always wondered why the repos are named after the _tools_ (`apt`, `yum`, `dnf`) even though the format of the packages is what defines the repo's structure more (e.g. both `yum` and `dnf` manage `.rpm` packages, `apt` manages `.deb` packages).

People brought up verbally:

- examples of projects which name their repos after the package formats: `deb.torproject.org`, `{deb,rpm}.releases.hashicorp.com`
- that `apt` and `yum` or `dnf` are also common
- :warning: that there is some additional effort involved in _changing_ the `apt.freedom.press` name (details: @eloquence)

For clarity what I had in mind was: `{deb,deb-test}.freedom.press` and `{rpm,rpm-test}.freedom.press`.

**Comment by eloquence** [comment]
My preference would be to keep hostname changes out of scope for this issue, since they will require downstream config changes and releases for SDW and SD Server and would substantially delay any kind of simplification -- and it's not clear to me that we gain sufficiently from changing hostnames to justify that cost.

**Comment by rocodes** [comment]
I'm also in support of keeping existing hostnames unchanged. No strong preference on repo names, change 'em however makes sense to you (I would be fine with saying goodbye to `securedrop-workstation-dev-rpm-packages-lfs`, doesn't quite roll off the tongue).

**Comment by creviera** [comment]
> For clarity what I had in mind was: {deb,deb-test}.freedom.press and {rpm,rpm-test}.freedom.press.

we could use a redirect (or create a mirror) for deb.freedom.press, too

**Comment by legoktm** [comment]
My priorities are, in order:
1. Less tab complete conflicts (i.e. I am against securedrop-deb- *and* securedrop-dnf- but not either of them individually)
2. Developer understanding (it's just maintainers who need to figure these out and all the names are sensible enough that we'll make do)

I agree that hostname should be kept separate from this conversation. Mostly because I think hostnames are a user facing change that needs more coordination and documentation, while moving Git repos is really trivial (once we agree of course) since GitHub automatically leaves redirects behind. I would note that all of the proposed names are significant improvements over the status quo. "Don't let perfect be the enemy of good."

My preference is:

* `securedrop-apt-test`
* `securedrop-apt-prod`

Earlier I said I didn't have a strong preference with apt vs deb, which is mostly true, but I lean apt because:
* On a technical devel, the repository and format is a property of APT, not dpkg. E.g. `/etc/apt/repos.d/sources.list`. dpkg has no knowledge of how to download things from somewhere, that's all APT.
* "deb" implies Debian, except we also have Ubuntu debs in our repo
* re: tabcomplete, avoiding "deb" keeps "dnf" open for rpms.

[Overall either is fine](https://bikeshed.toolforge.org/), at Wikimedia we had apt.wikimedia.org, so I'm used to it. OTOH there's deb.debian.org.

No preference on yum vs dnf. I tried to look around and see if there was a noticeable difference in how other people referred to them, I found recent (post-dnf) documentation calling them "[Yum repositories](https://www.redhat.com/sysadmin/add-yum-repository)", "[YUM/DNF repositories](https://www.redhat.com/sysadmin/ftp-yum-dnf-repository)", and my favorite, "[software repositories](https://docs.fedoraproject.org/en-US/quick-docs/adding-or-removing-software-repositories-in-fedora/)".

If hostname changes are on the table (again, don't think it should be), I'd advocate for a unified `packages.securedrop.org`, combining apt/deb/yum/dnf/rpm repos into one LFS repo and avoiding the entire terminology debate (no one else has mentioned how our apt repos are on freedom.press and our yum one is securedrop.org!). But I think it makes sense to wait to see how it shakes out for Dangerzone (c.f. https://github.com/freedomofpress/infrastructure/issues/3937) first, and we have plenty more work to do to set us up for merging repositories and automatically updating repo URLs (e.g. in https://github.com/freedomofpress/securedrop/issues/3286 I subtly proposed having securedrop-config be responsible for provisioning sources.list.d files).

**Comment by creviera** [comment]
> @cfm - Just throwing this on your radar in case you find time to incorporate a facilitated discussion in an upcoming SD team meeting around the other suggestions for our rpms and builder.

Thanks for responding to my request! We've now received sufficient feedback and food for thought for how we name packaging repos at FPF. (It was also helpful to know that the SecureDrop team wasn't expecting a vote.)

All input considered, and much appreciated, @maeve-fpf and I think it makes the most sense to stick with the original proposal in the issue description.

Given that one of our goals is to have some sort of naming convention and alignment between lfs and our hosted package repos, we decided to go with `securedrop-yum-{test|prod}` and `securedrop-apt-{test|prod}`. If instead we went with `securedrop-rpm-{test|prod}` and `securedrop-deb-{test|prod}` (which I prefer) then we'd also want to change the hosted package repo names to `rpm.securedrop.org` and `deb.securedrop.org` so that there's a naming alignment. This would be a larger change and would require more discussion (e.g. what @legoktm brought up around potentially consolidating hosted package repos to something like `packages.freedom.press` or `packages.securedrop.org`), and we just don't see enough justification for it. 

As a reminder, this work began as part of our Summer Cleanup sessions and while it's not a top priority it is something @maeve-fpf and I plan to make progress on in between higher-priority infra team work.

**Comment by eaon** [comment]
> If instead we went with securedrop-rpm-{test|prod} and securedrop-deb-{test|prod} then we'd also want to change the hosted package repo names to rpm.securedrop.org and deb.securedrop.org so that there's a naming alignment (notice I'm not saying deb.freedom.press).

This tingles the portion of my brain that loves consistency. IOW that would be my number 1 preference in this not-quite ranked-choice non-vote :wink:

**Comment by maeve-fpf** [comment]
Just wanted to chime in here that I think sticking with the original plan sounds best, for all the reasons mentioned:

- avoid potentially both starting with the same letter (for tab completion)
- deferring any discussion of changing hostnames (potential downstream breakage, doesn't have to be tied to repo names)
- consistency (current hostnames use `apt` and `yum` terminology, can be renamed again if we change hostnames)

So, I'm going to start with renaming `securedrop-debian-packaging` -> `securedrop-builder` today (after I post this), and we should be able to see that GitHub's built-in redirecting works. Tomorrow, @creviera and I will split up renaming the artifact repos.

**Comment by maeve-fpf** [comment]
That one rename is done: if you have a local clone of the repo, these commands should succeed:

```
git fetch # fetches from old url, silently redirected
git remote set-url origin git@github.com:freedomofpress/securedrop-builder.git
git fetch # fetches from new url
```
