### ISSUE TITLE
Configure required CI checks in this repo

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-builder#374]
Currently no CI checks are marked as required to merge into `main`. I would propose the following breakdown:

Required:
- build-bullseye-*
- lint-and-test
- reprotest-debs
- reprotest-wheels

Not required:
- build-bookworm-* (per agreed upon practice to treat these failures as independently resolvable if they're not introduced by a specific PR)

**Comment by legoktm** [comment]
+1 from me. I would note that in the past we've had weird failures on reprotest jobs (e.g., https://github.com/freedomofpress/securedrop-debian-packaging/issues/298, https://github.com/freedomofpress/securedrop-debian-packaging/issues/350), but the solution to that should probably be making the reprotest jobs easier to understand (maybe splitting it into more jobs) rather than making them not-required.

**Comment by legoktm** [comment]
Done via https://github.com/freedomofpress/infrastructure/issues/4784
